name: create-html
on: push

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build HTML file
        uses: actions/checkout@v4
      - run: |
           chmod +x ./scripts/build.sh
           curl -LJO https://github.com/commonmark/cmark/archive/0.29.0.tar.gz
           tar xzf cmark-0.29.0.tar.gz
           cd cmark-0.29.0
           make [INSTALL_PREFIX=/prefix]
           sudo make install
           cd ~/work/fredzia.github.io/fredzia.github.io/scripts
           ./build.sh
           ls

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
    steps:
    - name: Init new repo and commit generated files
      run: |
        cd ~/work/fredzia.github.io/fredzia.github.io/scripts && ls
      #git init
      #git add -A
      #git config --local user.email "action@github.com"
      #git config --local user.name "GitHub Action"
      #git commit -m 'Deploy'

    - name: Force push to destination branch
      uses: ad-m/github-push-action@v0.5.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
        force: true
        directory: ./
            
          
