name: create-html
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - run: |
           chmod +x ./scripts/build.sh
           curl -LJO https://github.com/commonmark/cmark/archive/0.29.0.tar.gz
           tar xzf cmark-0.29.0.tar.gz
           cd cmark-0.29.0
           make [INSTALL_PREFIX=/prefix]
           sudo make install
           cd ~/work/fredzia.github.io/fredzia.github.io/scripts
           ./build.sh
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: ~/work/fredzia.github.io/fredzia.github.io/index.html
          if-no-files-found: error
          overwrite: true

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 
            
          
