name: create-html
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run build script
      run: |
         chmod +x ./scripts/build.sh
         ./scripts/build.sh
         cd ..
      #working-directory: ../
      shell: bash

  upload-artifact:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/upload-artifact@v4
      with:
        name: html
        path: ./index.html
        if-no-files-found: error
        overwrite: true

  download-artifact:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v4.1.8
          
